#!/bin/sh

# FreeBSD rc.d script for spkrd - FreeBSD speaker device network server
#
# Add the following lines to /etc/rc.conf to enable spkrd:
#
# spkrd_enable="YES"
# spkrd_flags="--port 8080 --device /dev/speaker --retry-timeout 30"
#
# Available flags:
#   --port <port>           Server port (default: 8080)
#   --device <path>         Speaker device path (default: /dev/speaker)  
#   --retry-timeout <secs>  Device retry timeout (default: 30)
#
# Examples:
#   spkrd_flags="--port 3000"
#   spkrd_flags="--device /tmp/test-speaker --port 9000"
#   spkrd_flags="--retry-timeout 60 --port 8080"

. /etc/rc.subr

name=spkrd
rcvar=spkrd_enable

command="/usr/local/bin/${name}"
command_args="${spkrd_flags}"

pidfile="/var/run/${name}.pid"
required_files="/usr/local/bin/${name}"

load_rc_config $name
run_rc_command "$1"
